apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: application-service
  template:
    metadata:
      labels:
        app: application-service
    spec:
      containers:
      - name: application-service
        image: gcr.io/devops-hackathon-490406/application-service:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  type: LoadBalancer
  selector:
    app: application-service
  ports:
  - port: 80
    targetPort: 3001
